---
service: cb-tf-matt


frameworkVersion: ">=2.0.0"

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-plugin-ifelse



provider:
  name: aws
  region: ${self:custom.region}
  stage: ${opt:stage}



  runtime: nodejs12.x
  apiGateway:
    # https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
    shouldStartNameWithService: true


  stackPolicy:
    - Effect: ${self:custom.stackPolicyEffect.${self:provider.stage}, self:custom.stackPolicyEffect.default}
      Action: "Update:*"
      Principal: "*"
      Resource: "*"
   
    

custom:
  region: eu-west-2

  
  
  stackPolicyEffect:
    prod: Deny
    uat: Deny
    default: Allow

 
  

functions:
 
  hello-world:
    handler: handlers/hello.main
    events:
      - http:
          path: hello
          method: get
 