version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      # - npm install -g serverless
  build:
    commands:
      # - npm install

      # - sls deploy --stage cbversion

      - echo "hello from buildspec"