version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g serverless

  pre_build:
    commands:
      - aws cloudformation set-stack-policy --stack-name cb-tf-matt-prod --stack-policy-body file://codebuild/allow-policy.json
  build:
    commands:
      - npm install

      - sls deploy --stage prod

  post_build:
    commands:
      - aws cloudformation set-stack-policy --stack-name cb-tf-matt-prod --stack-policy-body file://codebuild/deny-policy.json

